server:
  port: ${SWAPEE_SERVICE_PORT:8088}

spring:
  datasource:
    url: ${SWAPEE_SERVICE_DB_URL:jdbc:mysql://localhost:3310/swapee-db}
    username: ${SWAPEE_SERVICE_DB_USERNAME:root}
    password: ${SWAPEE_SERVICE_DB_PASSWORD:root}
    maximumPoolSize: ${SWAPEE_SERVICE_DB_MAX_POOL:5}
  jpa:
    database-platform: ${SWAPEE_SERVICE_DB_PLATFORM:org.hibernate.dialect.MySQL8Dialect}
    hibernate:
      ddl-auto: ${SWAPEE_SERVICE_DB_DDL_AUTO:create} # change to update
    show-sql: ${SWAPEE_SERVICE_DB_SHOW_SQL:false}
    properties:
      hibernate:
        generate_statistics: ${SWAPEE_SERVICE_DB_STAT:false}









