name: "swapee-cicd"

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/swapee .
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/swapee:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Install Docker
        run: |
          if ! command -v docker &> /dev/null; then
              sudo yum update -y
              sudo yum install -y yum-utils device-mapper-persistent-data lvm2
              sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
              sudo yum install -y docker-ce docker-ce-cli containerd.io
              sudo usermod -aG docker $(whoami)
              sudo systemctl restart docker
          fi
      - name: Pull Image From DockerHub
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/swapee:latest
      - name: Delete Old Container
        run: sudo docker rm -f swapee-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name swapee-container ${{ secrets.DOCKERHUB_USERNAME }}/swapee:latest